apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.project }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: dgc24.mobomo.net
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.project }}-web
            port:
              number: {{ .Values.containerPorts.web }}
        path: /
        pathType: Prefix
