---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project }}-secret-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.project }}
    role: secret-db
type: Opaque    
data:
  password: Mobomo2024
  rootPassword: Mobomo2024
