apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.project }}
    role: web
    tier: {{ .Values.tiers.web }}
spec:
  selector:
    app: {{ .Values.project }}
    role: web
  ports:
    - protocol: TCP
      port: {{ .Values.containerPorts.web }}
      targetPort: {{ .Values.containerPorts.web }}
